# This is a basic workflow to help you get started with Actions

name: Triggered Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run script
        run: echo "This is a triggered workflow"


      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: clone the repo
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install
          git secrets --scan
